/*
 * codegen.h  –  Three-Address Code (TAC) generation, optimization,
 *               and target (stack-machine) code emission.
 *
 * TAC instruction format
 * ----------------------
 *   BINOP    :  result = arg1  op  arg2
 *   COPY     :  result = arg1
 *   LABEL    :  label:
 *   GOTO     :  goto   label
 *   IF_FALSE :  ifFalse arg1 goto label
 *   PRINT    :  print  arg1
 *   NOP      :  (no-op; dead instructions are marked and skipped)
 *
 * Temporaries : t1, t2, …   (auto-generated by tac_new_temp)
 * Labels      : L1, L2, …   (auto-generated by tac_new_label)
 */

#ifndef CODEGEN_H
#define CODEGEN_H

#include "ast.h"
#include <stdio.h>

/* ------------------------------------------------------------------ */
/* TAC instruction type                                                */
/* ------------------------------------------------------------------ */
typedef enum {
    TAC_BINOP,
    TAC_COPY,
    TAC_LABEL,
    TAC_GOTO,
    TAC_IF_FALSE,
    TAC_PRINT,
    TAC_NOP
} TACType;

/* ------------------------------------------------------------------ */
/* A single TAC instruction (linked-list node)                        */
/* ------------------------------------------------------------------ */
typedef struct TACInstr {
    TACType  type;
    char    *result;      /* destination variable / temp               */
    char    *arg1;        /* first  source operand                     */
    char    *op;          /* operator string  (+, -, *, /, <, >, ==, !=) */
    char    *arg2;        /* second source operand                     */
    char    *label;       /* label name (LABEL / GOTO / IF_FALSE)      */
    int      is_dead;     /* 1 = eliminated by dead-code pass          */
    struct TACInstr *next;
} TACInstr;

/* ------------------------------------------------------------------ */
/* The instruction list with counters for fresh name generation        */
/* ------------------------------------------------------------------ */
typedef struct {
    TACInstr *head;
    TACInstr *tail;
    int       temp_count;
    int       label_count;
} TACList;

/* ---- TAC list management ---- */
TACList  *tac_create       (void);
void      tac_destroy      (TACList *tl);
char     *tac_new_temp     (TACList *tl);     /* returns owned string  */
char     *tac_new_label    (TACList *tl);     /* returns owned string  */

/* ---- Emit helpers ---- */
TACInstr *tac_emit         (TACList *tl, TACType type,
                             const char *result, const char *arg1,
                             const char *op,    const char *arg2);
TACInstr *tac_emit_label   (TACList *tl, const char *label);
TACInstr *tac_emit_goto    (TACList *tl, const char *label);
TACInstr *tac_emit_if_false(TACList *tl, const char *cond,
                             const char *label);
TACInstr *tac_emit_print   (TACList *tl, const char *arg);

/* ---- Code generation from AST ---- */
char    *codegen_expr (TACList *tl, ASTNode *node);  /* returns temp name */
void     codegen_stmt (TACList *tl, ASTNode *node);
TACList *codegen      (ASTNode *root);

/* ---- Optimization passes ---- */
void optimize(TACList *tl);

/* ---- Output ---- */
void tac_write       (TACList *tl, FILE *out); /* human-readable TAC    */
void target_codegen  (TACList *tl, FILE *out); /* stack-machine pseudo-asm */

#endif /* CODEGEN_H */
